config/routes.rb
Rails.application.routes.draw do
  resources :posts 
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def find
	@post = Post.find(params[:id])
  end

  def index
  	@posts = Post.all
  end

  def show
  	@find
  end

  def new
  	@post = Post.new
  end

  def edit
  	@find
  end

  def create
  	@post = Post.new(post_form)
  	
  	if @post.save
  		redirect_to @post
  	else
  		render 'new'
  	end
  end

  def update
  	@find

  	if @post.update(post_form)
  		redirect_to @post
  	else
  		render 'edit'
  	end
  end

  def destroy
  	@find
  	@post.destroy

  	redirect_to posts_path
  end

  private
  	def post_form
  		params.require(:post).permit(:title, :text)
  	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class='container'>
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with model: @post, local: true do |form| %>
 
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@post.errors.count, "error") %> prohibited
        this post from being saved:
      </h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
 
<% end %>

app/views/posts/index.html.erb
<h1>Post List</h1>

<button onclick="location.href='/posts/new'" class="btn btn-primary new">New Post</button>
<div class="row">
	<div class="col-md-6 col-xs-6">
		<table class="table">
		  <tr>
		  	<th>No</th>
		    <th>Title</th>
		    <th>Text</th>
		    <th>Action</th>
		  </tr>
		 
		  <% @posts.each_with_index do |post,i| %>
		    <tr>
		      <td><%= i+1 %></td>
		      <td><%= post.title %></td>
		      <td><%= post.text %></td>
		      <td><%= link_to 'Show', post_path(post) %></td>
		    </tr>
		  <% end %>
		</table>
	</div>
	<div class="col-md-6 col-xs-6">
		 <%= image_tag("kraken.jpg", class: "img-fluid")%> 
	</div>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<a href="/posts" class="btn btn-primary">Back</a>
<%= render 'form' %>

app/views/welcome/index.html.erb
<h1>Welcome To The Page</h1>
<a href="/posts">To Post List</a>